[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]

[[headers]]
  for = "/news.json"
  [headers.values]
    Cache-Control = "public, max-age=1800"

[[headers]]
  for = "/waves.gif"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
